package com.omni.app.data.download

import java.util.UUID

enum class DownloadStatus {
    QUEUED,
    FETCHING_INFO,
    DOWNLOADING,
    CONVERTING,
    EMBEDDING,
    COMPLETED,
    FAILED,
    CANCELLED
}

enum class DownloadType { VIDEO, AUDIO }

enum class CookieSource(val label: String) {
    NONE("None"),
    CHROME("Chrome"),
    FIREFOX("Firefox"),
    EDGE("Edge"),
    BRAVE("Brave"),
    FILE("From file")
}

enum class SponsorBlockAction(val label: String) {
    SKIP("Skip"),
    MARK("Mark"),
    REMOVE("Remove")
}

data class AvailableFormat(
    val formatId: String,
    val height: Int?,
    val fps: Int?,
    val ext: String,
    val filesize: Long?,
    val label: String
)

data class DownloadItem(
    val id: String = UUID.randomUUID().toString(),
    val url: String,
    val title: String = "Fetching...",
    val author: String = "Unknown",
    val thumbnailUrl: String? = null,
    val type: DownloadType,
    val quality: String,
    val selectedFormatId: String? = null,
    val format: String,
    val prefer60fps: Boolean = true,
    val embedThumbnail: Boolean = true,

    // ── Subtitles ──────────────────────────────────────────────────
    val embedSubtitles: Boolean = false,
    val subtitleLanguage: String = "en",
    val subtitleFormat: String = "srt",
    val autoGeneratedSubtitles: Boolean = false,

    // ── Chapters & Metadata ────────────────────────────────────────
    val embedChapters: Boolean = false,
    val splitByChapters: Boolean = false,
    val writeMetadata: Boolean = true,

    // ── SponsorBlock ───────────────────────────────────────────────
    val sponsorBlockEnabled: Boolean = false,
    val sponsorBlockCategories: Set<String> = setOf("sponsor"),
    val sponsorBlockAction: SponsorBlockAction = SponsorBlockAction.SKIP,

    // ── Time range ─────────────────────────────────────────────────
    val startTime: String = "",
    val endTime: String = "",

    // ── Audio post-processing ──────────────────────────────────────
    val normalizeAudio: Boolean = false,
    val trimSilence: Boolean = false,

    // ── Network & Cookies ──────────────────────────────────────────
    val cookieSource: CookieSource = CookieSource.NONE,
    val cookieFilePath: String? = null,
    val speedLimit: String = "",
    val proxy: String = "",
    val maxFragments: Int = 16,

    // ── Output ─────────────────────────────────────────────────────
    val outputTemplate: String = "%(title)s.%(ext)s",
    val customArgs: String = "",

    // ── Runtime status (not set by user) ───────────────────────────
    val outputPath: String? = null,
    val status: DownloadStatus = DownloadStatus.QUEUED,
    val progress: Float = 0f,
    val speed: String = "",
    val eta: String = "",
    val errorMessage: String? = null,
    val fileSize: String = "",
    val batchId: String? = null,
    val addedAt: Long = System.currentTimeMillis()
)
